ALTER TABLE users
DROP PRIMARY KEY,
CHANGE COLUMN id login_id VARCHAR(64),
ADD COLUMN id VARCHAR(64) NOT NULL PRIMARY KEY DEFAULT MD5(RAND()),
ADD COLUMN organization_id VARCHAR(64) NOT NULL;

CREATE TABLE organization_settings (
   id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   organization_id VARCHAR(64) NOT NULL,
   name VARCHAR(32) NOT NULL,
   value VARCHAR(32) NOT NULL,
   last_changed_by VARCHAR(64) NOT NULL,
   last_changed_at BIGINT NOT NULL
);

CREATE TABLE organizations (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    hash VARCHAR(64) NOT NULL,
    code VARCHAR(6) NOT NULL,
    created_at BIGINT NOT NULL
);

ALTER TABLE payments
ADD COLUMN organization_id VARCHAR(64) NOT NULL;

ALTER TABLE beers
ADD COLUMN organization_id VARCHAR(64) NOT NULL;

ALTER TABLE beer_purchases
ADD COLUMN organization_id VARCHAR(64) NOT NULL;