ALTER TABLE users
DROP PRIMARY KEY id,
RENAME COLUMN id login id,
ADD COLUMN id VARCHAR(64) NOT NULL PRIMARY KEY DEFAULT MD5(RAND()),
ADD COLUMN organization_id VARCHAR(64) NOT NULL;

CREATE TABLE organizations (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    hash VARCHAR(64) NOT NULL,
    code VARCHAR(6) NOT NULL,
    created_at BIGINT NOT NULL,
)

ALTER TABLE payments
ADD COLUMN organization_id VARCHAR(64) NOT NULL;